# Generated by Django 5.2.17 on 2026-10-02 21:39

import apps.pedidos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('filiais', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('codigo', models.CharField(default=apps.pedidos.models.gerar_codigo_pedido, max_length=20, unique=True, verbose_name='código')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_SEPARACAO', 'Em separação'), ('SEPARADO', 'Separado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='filiais.loja', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'sb_pedido',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='produtos.produto', verbose_name='produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'db_table': 'sb_item_pedido',
                'ordering': ['pedido', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Separacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20, verbose_name='status')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='conclusão')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separacoes', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'separação',
                'verbose_name_plural': 'separações',
                'db_table': 'sb_separacao',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
