# Generated by Django 5.2.17 on 2026-10-02 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='separacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separacoes', to=settings.AUTH_USER_MODEL, verbose_name='separador'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['loja', 'status'], name='sb_pedido_loja_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['data_criacao'], name='sb_pedido_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='sb_item_pedido_produto_uniq'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='sb_item_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.CheckConstraint(condition=models.Q(('preco_unitario__gt', 0)), name='sb_item_preco_positivo'),
        ),
        migrations.AddConstraint(
            model_name='separacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'EM_ANDAMENTO')), fields=('pedido',), name='sb_separacao_uma_ativa_por_pedido'),
        ),
    ]
