# Generated by Django 5.2.17 on 2026-10-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='separado',
            field=models.BooleanField(default=False, verbose_name='separado'),
        ),
    ]
