# Generated by Django 5.2.17 on 2026-10-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
        ('pedidos', '0003_itempedido_separado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pagamentos.formapagamento', verbose_name='forma de pagamento'),
        ),
    ]
