# Generated by Django 5.2.17 on 2026-10-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('filiais', '0001_initial'),
        ('pagamentos', '0002_formas_pagamento_iniciais'),
        ('pedidos', '0004_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.TextField(blank=True, default='', verbose_name='endereço de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RETIRADA', 'Retirada na loja'), ('DOMICILIO', 'Entrega em domicílio')], default='RETIRADA', max_length=20, verbose_name='tipo de entrega'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_entrega', 'DOMICILIO'), _negated=True), models.Q(('endereco_entrega', ''), _negated=True), _connector='OR'), name='sb_pedido_domicilio_com_endereco'),
        ),
    ]
