# Generated by Django 5.2.17 on 2026-10-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_SEPARACAO', 'Em separação'), ('SEPARADO', 'Separado'), ('SAIU_PARA_ENTREGA', 'Saiu para entrega'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='status'),
        ),
    ]
