# Generated by Django 5.2.17 on 2026-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='telefone')),
                ('horario_abertura', models.TimeField(verbose_name='horário de abertura')),
                ('horario_fechamento', models.TimeField(verbose_name='horário de fechamento')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'db_table': 'sb_loja',
                'ordering': ['nome'],
            },
        ),
    ]
