# Generated by Django 5.2.17 on 2026-10-02 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiais', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='quantidade')),
                ('quantidade_minima', models.IntegerField(default=0, verbose_name='quantidade mínima')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='filiais.loja', verbose_name='loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='produtos.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'estoque local',
                'verbose_name_plural': 'estoques locais',
                'db_table': 'sb_estoque_local',
                'ordering': ['loja', 'produto'],
                'indexes': [models.Index(fields=['loja', 'quantidade'], name='sb_estoque_loja_qtd_idx')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'loja'), name='sb_estoque_produto_loja_uniq'), models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='sb_estoque_quantidade_nao_negativa'), models.CheckConstraint(condition=models.Q(('quantidade_minima__gte', 0)), name='sb_estoque_minimo_nao_negativo')],
            },
        ),
    ]
