# Generated by Django 5.2.17 on 2026-10-02 21:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('categoria', models.CharField(choices=[('HORTIFRUTI', 'Hortifrúti'), ('MERCEARIA', 'Mercearia'), ('BEBIDAS', 'Bebidas'), ('LATICINIOS', 'Laticínios e frios'), ('PADARIA', 'Padaria'), ('ACOUGUE', 'Açougue'), ('LIMPEZA', 'Limpeza'), ('HIGIENE', 'Higiene e beleza')], default='MERCEARIA', max_length=20, verbose_name='categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'sb_produto',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='sb_produto_nome_idx'), models.Index(fields=['categoria', 'ativo'], name='sb_produto_cat_ativo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('preco__gt', 0)), name='sb_produto_preco_positivo')],
            },
        ),
    ]
