# Generated by Django 5.2.17 on 2026-10-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='produtos/', verbose_name='foto'),
        ),
    ]
