# Generated by Django 5.2.17 on 2026-10-03 03:52

import apps.produtos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=14, validators=[apps.produtos.validators.validar_codigo_barras], verbose_name='código de barras'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras', ''), _negated=True), fields=('codigo_barras',), name='sb_produto_codigo_barras_uniq'),
        ),
    ]
