# Generated by Django 5.2.17 on 2026-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('PIX', 'Pix'), ('CREDITO', 'Cartão de crédito'), ('DEBITO', 'Cartão de débito'), ('DINHEIRO', 'Dinheiro'), ('VALE_ALIMENTACAO', 'Vale-alimentação')], max_length=20, verbose_name='tipo')),
                ('permite_troco', models.BooleanField(default=False, help_text='Indica se o cliente pode pedir troco (ex.: dinheiro).', verbose_name='permite troco')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'db_table': 'sb_forma_pagamento',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['ativa', 'ordem'], name='sb_forma_pag_ativa_ordem_idx')],
            },
        ),
    ]
